# Generated by Django 5.0.3 on 2024-06-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Queries",
            fields=[
                (
                    "queryid",
                    models.BigAutoField(
                        db_column="QueryID", primary_key=True, serialize=False
                    ),
                ),
                ("querycontent", models.TextField(db_column="QueryContent")),
                ("querytime", models.DateTimeField(db_column="QueryTime")),
            ],
            options={
                "db_table": "queries",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Queryhistory",
            fields=[
                (
                    "historyid",
                    models.AutoField(
                        db_column="HistoryID", primary_key=True, serialize=False
                    ),
                ),
                ("userid", models.PositiveBigIntegerField(db_column="UserID")),
                ("executiontime", models.DateTimeField(db_column="ExecutionTime")),
            ],
            options={
                "db_table": "queryhistory",
                "managed": False,
            },
        ),
    ]
